### ISSUE TITLE
ECS Agent Multi-Region Resiliency

### ISSUE THREAD

**Issue by desponda** [aws/amazon-ecs-init#107]
In our corporate AWS configuration we have restricted west instances to only be able to talk to west buckets, east instances to be able to only talk to east buckets since the tarballs are only hosted on the east bucket as seen on 
https://github.com/aws/amazon-ecs-init/blob/dev/ecs-init/config/release.go#L20
then we cannot use ecs-init to bootstrat our Amazon Linux instances.

In addition, wouldn't it be better for resiliency in case us-east-1 goes down to have the bucket in multiple regions?

**Comment by learnaws** [comment]
facing the same issue

**Comment by buttonbuilder** [comment]
👍

**Comment by buttonbuilder** [comment]
+1

**Comment by desponda** [comment]
I guess more specifically, it looks like if we add more regions here: https://github.com/aws/amazon-ecs-init/blob/f885f5923415e643d3d6937ee0b8e2b2f4cd61ef/ecs-init/config/common.go#L42-L45 it would work

**Comment by jamisonhyatt** [comment]
Also facing the same issue.

**Comment by richardpen** [comment]
Thank you all for reporting this, originally the ecs-agent was only stored in `us-east-1`, and it was replicated to `cn-north-1` when we support the BJS region. Since then I think it is reasonable to replicate the ecs-agent to all the regions to support the use case above, beyond that we also need to make some change to the ecs-init to support downloading from specified region. I'll mark this as a feature request, please keep tracking this for updates.

Thanks,
Peng

**Comment by desponda** [comment]
@richardpen you already have support for this you just need to upload to additional buckets and update these lines of code: 
https://github.com/aws/amazon-ecs-init/blob/f885f5923415e643d3d6937ee0b8e2b2f4cd61ef/ecs-init/config/common.go#L42-L45

This is pretty important for high-availability especially with the 2 major recent AWS s3 outages in us-east-1 any way you can prioritize it, shouldn't take a lot of time?

**Comment by jahkeup** [comment]
Regional buckets are now used by `amazon-ecs-init` with #170. It is worth noting that the [downloader's behavior](https://github.com/fenxiong/amazon-ecs-init/blob/10739153085014a075c8712b2bd3a7b8c7270a7d/ecs-init/cache/cache.go#L94-L118) is to attempt a download from the bucket in `us-east-1` first and then fail over to the instance's region's bucket (eg: an instance in `us-west-2` will attempt download from a bucket in `us-east-1` and then `us-west-2`).

Please feel free to reopen and comment if and why this doesn't satisfy your environment's needs so that we can drive the appropriate change.

Thanks for the input folks!
