### ISSUE TITLE
Docker Daemon Logs Not Being Rotated?

### ISSUE THREAD

**Issue by Strainy** [aws/amazon-ecs-init#119]
Hi there,

Noticing this on the ECS Optimised AMI `2017.03.f`:

```
[root@ip-10-14-23-58 log]# du -ha | grep docker
851M	./docker
```

Just looks to container Docker daemon logs:

```
[root@ip-10-14-23-58 log]# tail -n 5 docker
time="2017-10-09T22:11:54.979491178Z" level=error msg="Handler for GET /v1.17/containers/2aa368aae18e2c066f5ac375af2779351c9c802a951f205a08536265d61f8813/json returned error: No such container: 2aa368aae18e2c066f5ac375af2779351c9c802a951f205a08536265d61f8813"
time="2017-10-09T22:42:16.244102384Z" level=info msg="Container de644dfc59e4ec25d63d9339b2531d3fef562107384a8e61d38bd3b253ac1774 failed to exit within 30 seconds of signal 15 - using the force"
time="2017-10-09T23:12:16.520693171Z" level=error msg="Handler for GET /v1.17/containers/204ae4cab609c90b9e13c889f6d767082d0404f7d27c5c184b6f4233eafa1c7b/json returned error: No such container: 204ae4cab609c90b9e13c889f6d767082d0404f7d27c5c184b6f4233eafa1c7b"
time="2017-10-09T23:12:16.553052378Z" level=error msg="Handler for GET /v1.17/containers/de644dfc59e4ec25d63d9339b2531d3fef562107384a8e61d38bd3b253ac1774/json returned error: No such container: de644dfc59e4ec25d63d9339b2531d3fef562107384a8e61d38bd3b253ac1774"
time="2017-10-09T23:47:23.114060944Z" level=error msg="Handler for GET /v1.17/containers/b61c41d7ab9e5f3604b7084f5e382d7e5ec278d1b1fba822fac09807dc7ff95e/json returned error: No such container: b61c41d7ab9e5f3604b7084f5e382d7e5ec278d1b1fba822fac09807dc7ff95e"
```

Where can I find the log rotation settings for this file? As I've experienced it filling up my root disk in past where I have high volumes of traffic running through my containers and an error with a logging driver occurs (i.e. FluentD agent dies or starts generating buffer overflow errors under load, so Docker deamon starts writing the log lines out to disk saying that it couldn't forward the logs):
https://github.com/moby/moby/issues/34974

Any assistance that you can offer on this front would be much appreciated.

**Comment by jhaynes** [comment]
Hi @Strainy, 

Sorry you're running into this. Docker's logs are not rotated by default on Amazon Linux, but you can set up log rotation via a few different methods. A common option is to use [logrotate](https://linux.die.net/man/8/logrotate). Or you can explore setting the `--log-opt max-size` option via `/etc/sysconfig/docker` or in the `daemon.json` config as documented [here](https://docs.docker.com/engine/admin/logging/json-file/).

I'm going to close this for now since it isn't directly related to `ecs-init`, but I have logged it internally as a feature request in our ECS Optimized AMI.

**Comment by Strainy** [comment]
Hi @jhaynes,

Right, this caught me off guard. Those logs are just set to grow unconstrained indefinitely?

I have attempted to use logrotate, but new files are created with the current date appended to the file continually until logrotate somehow doesn't recognise the file name anymore and the Docker daemon resumes writing it's logs.

Additionally, the log-opts you're referring to have no affect on the daemon logs, this option is only  for setting the default log options for the logging driver ascribed to containers.

According to [this issue](https://github.com/moby/moby/issues/34974) the logging for the Docker daemon is managed by the init system. So I don't think this issue should be closed.

**Comment by jhaynes** [comment]
Sorry that it was unexpected. Yes, without configuration, the Docker daemon logs will grow.

The Docker daemon is managed by the init system. However, this package (`ecs-init`) is only responsible for running the `ecs-agent` which is why I closed this issue. Docker is managed by upstart on Amazon Linux. This [Docker issue](https://github.com/moby/moby/issues/7333) has some suggestions for how to get log rotation working. 

You're correct about the docs I linked to, I was just trying to cover all my bases in case I didn't understand your question. Sorry for not making that clearer.

**Comment by hltbra** [comment]
This log rotation is even more critical when AWS support ask you to enable debug mode to help you troubleshoot ECS issues. The [ECS troubleshooting documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-debug-mode.html) mentions the `-D` option to enable debug mode in docker (which will add more logs!), but it doesn't give any instructions to set this up via user-data or how to make sure log rotation is configured.

I use the ECS optimized AMI (amzn-ami-2017.03.g-amazon-ecs-optimized) and expected such log to be rotated for me instead of adding this to user-data. I believe this is a surprise for many people. Is your team responsible for creating the ECS optimized AMI, @jhaynes? Would it make sense for me to open an AWS support ticket for this?

For those in the same situation as me, this is the bottom of my new user-data script:
```shell
# -- docker & ecs debug mode ---
# enable debug logs to have more information when troubleshooting & opening tickets.
# by default the ECS agent does log rotation of its regular & audit logs.
echo ECS_LOGLEVEL=debug >> /etc/ecs/ecs.config
sed -i 's/^OPTIONS="/OPTIONS="-D /' /etc/sysconfig/docker

service docker restart
start ecs

# -- end of docker & ecs debug mode ---


# --- docker log rotation ---
# these log rotate configs were inspired by Kubernetes:
# https://github.com/kubernetes/kubernetes/tree/8fd414537b5143ab039cb910590237cabf4af783/cluster/saltbase/salt/logrotate

# rotate the docker daemon log when it reaches 100MB and keep at most 5 log files
cat <<EOF > /etc/logrotate.d/docker
/var/log/docker {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 100M
    dateext
    dateformat -%Y%m%d-%s
    create 0644 root root
}
EOF

# make sure logrotate is executed hourly (the ECS optimized AMI does daily rotations by default)
cat <<EOF > /etc/cron.hourly/logrotate
/usr/sbin/logrotate /etc/logrotate.conf
EOF

# --- end of docker log rotation ---
```

@Strainy: did you solve your problem in a similar way?

**Comment by jhaynes** [comment]
@hltbra Thanks for the additional info and I agree that we can improve our documentation and default configuration here. 

My team does own the ECS Optimized AMI and we're tracking this internally as a feature request. That said, you're welcome to open a support case because we always like to have the extra customer information.

**Comment by levigroker** [comment]
@jhaynes Any update on the best practice here? We are still suffering from this and though there are log configuration options in the task definition it would be better (for us?) to set this up through our user data scripts.

Thanks.

**Comment by kyleian** [comment]
Has this feature request moved forward at all? (@hltbra Could you link your support ticket if it's public?)

**Comment by hltbra** [comment]
@kyleian I searched through my support tickets and couldn't find anything. I don't think I opened a ticket for this, but we've been using the snippet I shared in production for 1.5 years.

**Comment by levigroker** [comment]
🙄
