### ISSUE TITLE
The docker ps command should show the agent version that's actually running instead of always showing "latest"

### ISSUE THREAD

**Issue by jtoberon** [aws/amazon-ecs-init#132]
ecs-init uses "amazon/amazon-ecs-agent:latest" for the image name of the ecs-agent container, so the docker ps command always shows that "latest" is running. Instead, the docker ps command should show the actual running version, e.g. "amazon/amazon-ecs-agent:1.15.2".

**Comment by Alonreznik** [comment]
I have also the problem, which makes us delayed in our deployment, that based on the --init property on the new ecs-agent's version.
Please fix asap.

**Comment by adnxn** [comment]
@jtoberon @Alonreznik If you're trying to determine the agent version, we'd recommend using the agent's [introspection api](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-introspection.html) instead of `docker ps`. Executing `$curl http://localhost:51678/v1/metadata` will return the agent version and commit hash. Please let us know if your use-case involves something beyond that.
