### ISSUE TITLE
Can you provide the instruction to install this on Centos 7?

### ISSUE THREAD

**Issue by kyangmove** [aws/amazon-ecs-init#24]

**Comment by samuelkarp** [comment]
Hi @kyangmove,

You can run the ECS Agent on CentOS (with Docker >= 1.7.0) by doing the following:

```
sudo mkdir -p /var/log/ecs
sudo mkdir -p /var/lib/ecs/data

sudo docker run --name ecs-agent \
        --privileged \
        --restart=on-failure:10 \
        --detach=true \
        --volume=/var/run/docker.sock:/var/run/docker.sock \
        --volume=/var/log/ecs/:/log:Z \
        --volume=/var/lib/ecs/data:/data:Z \
        --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
        --volume=/var/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro \
        --publish=127.0.0.1:51678:51678 \
        --env=ECS_LOGFILE=/log/ecs-agent.log \
        --env=ECS_LOGLEVEL=info \
        --env=ECS_DATADIR=/data \
        --env=ECS_CLUSTER=default \
        "amazon/amazon-ecs-agent:latest"
```

Note that the `--privileged` flag is needed because, by default, a SELinux policy prevents the Agent from accessing `/var/run/docker.sock`. Alternately, if you prefer to modify the SELinux policy applied to files in `/var/run/docker` rather than running the container with `--privileged`, you can use [this SELinux module](https://github.com/dpw/selinux-dockersock ) (by following the instructions in the README) and remove the `--privileged` flag from the command listed above.

The ecs-init package is not currently available for CentOS, but we'd be happy to take pull requests from you or from the CentOS project with appropriate modifications.

Thanks,
Sam

**Comment by mdamir** [comment]
@samuelkarp Should this really be such a big change for releasing for centOs?
