### ISSUE TITLE
Supply released packages (rpm) on GitHub

### ISSUE THREAD

**Issue by rickard-von-essen-iz** [aws/amazon-ecs-init#58]
It would be convenient to if you could provide packages for download from the [Releases page](https://github.com/aws/amazon-ecs-init/releases).

**Comment by samuelkarp** [comment]
@rickard-von-essen-iz RPMs are normally made available in the Amazon Linux AMI's [yum repositories](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-software.html).  We build the RPMs specifically for the Amazon Linux AMI and do not verify that they install correctly on other Linux systems.  Are you intending to use ecs-init on a different Linux system?

**Comment by rickard-von-essen-iz** [comment]
I intend to a) Download and inspect the RPM and/or b) repackage it for your OS/requirements.

Currently I have to launch a Amazon Linux EC2 install `yum-utils` and download the rpm there and then transfer it to our servers. This is further complicated by woking in a regulated industry and thus our instances are blocked from _Amazon Linux yum repositories_. And they are not exactly browsable so I can't easily download the rpm from the repo without Amazon Linux.

**Comment by samuelkarp** [comment]
@rickard-von-essen-iz Thanks, that helps clarify.

If you're modifying/repackaging the RPM anyway, it might be easier to do so from source.  The whole source code is already in this repository, and the spec file we use for the RPM on the Amazon Linux AMI is [located here](https://github.com/aws/amazon-ecs-init/blob/v1.12.1-1/packaging/amazon-linux-ami/ecs-init.spec).  If you check it out from source (and you have `golang` >= 1.3 installed) you should be able to run `make rpm` or `make srpm` to build the RPM and SRPM respectively.

We also have a spec file for SUSE checked in (though it has not been updated since 1.7.1).  If you're preparing packaging for a publicly-available Linux distribution we would be interested in getting that checked in here too.

**Comment by rickard-von-essen-iz** [comment]
Sorry for the slow response here. Rebuild the binary is easy but reproducing a rpm is more tricky since it heavily depends on the build environment.

Most importantly I think it's good practice for OSS projects to publish both source code and release binaries. Your releases are not easily available.

**Comment by samuelkarp** [comment]
@rickard-von-essen-iz As of today, you no longer need to launch an EC2 instance to access the Amazon Linux yum repositories.  We've also published an [Amazon Linux Container Image](https://aws.amazon.com/blogs/aws/new-amazon-linux-container-image-for-cloud-and-on-premises-workloads/) to help you use Amazon Linux locally.

Using the Amazon Linux Container Image, you can download the `ecs-init` RPM like this:

```
DESTINATION=$(pwd)
docker run -v "${DESTINATION}:/destdir" 137112412989.dkr.ecr.us-west-2.amazonaws.com/amazonlinux:latest sh -c "cd /destdir && yum -y install yum-utils && yumdownloader ecs-init"
```

**Comment by rickard-von-essen-iz** [comment]
Awesome! Exactly what I was looking for in the first place.

Just a side note if someone finds this: You need to login to the ECR to pull the `amazonlinux` docker image.
