### ISSUE TITLE
ECS_UPDATE_DOWNLOAD_DIR appears to be hardcoded to /var/cache/ecs.

### ISSUE THREAD

**Issue by jason-riddle** [aws/amazon-ecs-init#63]
When I install <code>ecs-init</code> and start the <code>ecs</code> service, the <code>agent.tar</code> appears to always be downloaded to <code>/var/cache/ecs</code>. My <code>/etc/ecs/ecs.config</code> looks like the following.

```
ECS_CLUSTER=kitchen-ecs-dev-cluster
ECS_AVAILABLE_LOGGING_DRIVERS=["json-file", "awslogs"]
ECS_CHECKPOINT=true
ECS_DATADIR=/etc/ecs/data
ECS_LOGLEVEL=debug
ECS_LOGFILE=/var/log/ecs/ecs-agent.log
ECS_UPDATES_ENABLED=false
ECS_UPDATE_DOWNLOAD_DIR=/etc/ecs/cache
ECS_RESERVED_MEMORY=256
ECS_SELINUX_CAPABLE=true
ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=10m
ECS_CONTAINER_STOP_TIMEOUT=10s
ECS_ENABLE_TASK_IAM_ROLE=true
ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
HTTP_PROXY=http://my-proxy:8099
HTTPS_PROXY=http://my-proxy:8099
NO_PROXY=169.254.169.254,/var/run/docker.sock
```

So I expect updates to be downloaded to <code>/etc/ecs/cache</code>. Any thoughts?

**Comment by samuelkarp** [comment]
Hi @jason-riddle,

The `/etc/ecs/ecs.config` file configures values that are sent to the ECS agent, but not ecs-init itself.  ecs-init does hard-code the cache directory to `/var/cache/ecs` and then mounts that directory as a volume inside the agent container so that the agent can download new versions of itself; `ECS_UPDATE_DOWNLOAD_DIR` controls where the agent will place the new versions inside the container after downloading (which you'd generally want to keep the same as the container-visible side of the mount).

ecs-init is a bit opinionated right now about where it places things on disk, but we're interested in understanding the customizations that you're trying to set.  Is there a specific reason you're attempting to have updates downloaded to `/etc/ecs/cache` instead of `/var/cache/ecs`?

Sam

**Comment by jason-riddle** [comment]
I was just trying to keep similar things grouped together (/etc/ecs/data for the data directory, /etc/ecs/cache for the cache directory). I didn't realize that /var/cache was a part of the Linux Filesystem Hierarchy until just a moment ago, so I'm going to go ahead and close this issue.
