### ISSUE TITLE
`status ecs` returns 0 when service is not running

### ISSUE THREAD

**Issue by thesmith** [aws/amazon-ecs-init#93]
I guess it should be returning a 3, but it returns a 0:

```
status ecs
ecs stop/waiting
echo $?
0
```

http://www.tldp.org/LDP/abs/html/exit-status.html

**Comment by jhaynes** [comment]
Hi @thesmith, 

This behavior is related to the init system, upstart, rather than ECS directly. Other upstart managed services behave similarly. The `0` exit code can be viewed as a successfully run `status` command rather than information about the service. Instead, that information is contained in the string `stop/waiting`.

If you have other questions, feel free to re-open this issue or create a new one.
